name: inject_generator
version: 1.0.0-alpha+1
description: Dev-time dependency for package:inject.
authors:
  - Matan Lurey <matanl@google.com>
  - Yegor Jbanov <yjbanov@google.com>
homepage: https://pub.dartlang.org/packages/inject

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: ^1.4.0
  build: ^2.0.0
  code_builder: ^3.7.0
  collection: ^1.15.0
  dart_style: ^2.0.0
  logging: ^1.0.1
  meta: ^1.3.0
  path: ^1.8.0
  quiver: ^3.0.1
  stack_trace: ^1.10.0

dev_dependencies:
  build_runner: ^1.12.2
  build_test: ^2.0.0
  inject:
    path: ../inject
  test: ^1.16.8
